### ISSUE TITLE
만약 argv가 들어오지 않게 된다면 이때 어떤 값이 들어가게 되나요?

### ISSUE THREAD

**Issue by JangHanbin** [heaeat/arp_send#4]
https://github.com/heaeat/send_arp/blob/968e9a747c299b4b0d8155318b00ca30dae3b33c/main.c#L34

**Comment by heaeat** [comment]
프로그램이 종료됨미다

**Comment by heaeat** [comment]
https://github.com/heaeat/send_arp/blob/32e59046fd678861f7f652f4edcf8e56224ff86b/main.cpp#L5
왜냐면 일케 바꿨거등여~
