### ISSUE TITLE
만약 아래와 같은 값들이 사정에 의해 변경되면 어떻게 해야하나요? 코드 가독성은요?

### ISSUE THREAD

**Issue by JangHanbin** [heaeat/arp_send#5]
https://github.com/heaeat/send_arp/blob/968e9a747c299b4b0d8155318b00ca30dae3b33c/main.c#L80

**Comment by heaeat** [comment]
https://github.com/heaeat/send_arp/blob/8a75cd492cd71065d07161ec9361c5bdbae2095a/main.cpp#L32
와 같이 수정하였습니다. 
감사합니다!
